theme: cayman
title: Polish ASR speech datasets survey
description: The survey goal is source and organize information about speech datasets produced within 3 decades of ASR R&D in Poland. <br>
So far 48 unique speech datasets were identfied and catalogued (see PL ASR speech datasets Catalog).
Datasets were described by manually annotating 57 attributes (see Taxonomy), out of which N were analyzed for the first time (see Analysis)
The total size of documented Polish ASR speech datasets amounts to over 20000 hours of audio and nearly 2500 hours of transcribed speech.
One thousand hours worth speech datasets are available online free of charge and over 600 hours of datasets through commercial providers.
